spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '!QAZ@WSX#EDC'
  redis:
    host: localhost


local:
  fileserver:
    dir:  "/home/upload"
    path: file

#应用配置
resources:
 # log文件写入地址
 logdir: "/home/cctv/logs"

swagger:
  enabled: false

