spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 654321
  redis:
    host: localhost
server:
  port: 8081

local:
  fileserver:
    dir:  "D:\\TEMP"
    path: file


#应用配置
resources:
 # log文件写入地址
 logdir: "logs/"


swagger:
  enabled: true