spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 654321
  redis:
    host: localhost
server:
  port: 8081

upload:
  path: "D:\\TEMP"